---

- hosts: all
  become: true
  tasks:


    - name: update repository index
      ansible.builtin.apt:
        update_cache: yes

    - name: Remove php support for nginx
      ansible.builtin.apt:
        name: php-fpm
        state: absent

    - name: Remove nginx package
      ansible.builtin.apt:
        name: nginx
        state: absent
